### PR TITLE
Combine bindings and module finder into InterpreterContext entity

### LINKED ISSUE #88: Module Finder as the part of the Global Context
Derived from https://github.com/rexim/Morganey/pull/86#discussion_r70649028

### PR DESCRIPTION
**Pull request by rexim**
Close #88

### CODE REVIEW

**Comment by rexim** [comment]
@ForNeVeR @keddelzz could you guys take a look when you get a chance?

**Comment by rexim** [comment]
Just a quick follow-up :)

**Comment by ForNeVeR** [comment]
LGTM :+1:

**Comment by rexim** [comment]
Thank you Mr @ForNeVeR

**Pull request merged**
