### PR TITLE
Turn 'std' into its own subproject

### LINKED ISSUE #242: Create proper sub-project for 'std'
Split from #216 

Currently Morganey's std-lib exists in a subfolder of Morganey. This folder is manually zipped to produce the tiny-jar. This was implemented by me in the scope of #218. 

However I propose to change that: Instead of manually zipping the contents of the folder it would be a better solution to turn the std-folder in a sub-project. That would have the advantage, that the `build.sbt` file will be a cleaner and that this implements #216, because sub-projects are automatically included in the uber-jar.

### PR DESCRIPTION
**Pull request by keddelzz**
- [x] Move contents of 'std/' to 'std/src/main/resources/std/'
- [x] Update build.sbt
  - [x] Remove manual zipping of 'std/'
  - [x] Introduce 'std' subproject
  - [x] Copy 'std' tiny-jar into output dir of Morganey
- [x] Update hardcoded paths in Morganey-sources
## 

closes #242

### CODE REVIEW

**Review by 06needhamt — APPROVED** [review]
LGTM :+1:

**Review by ForNeVeR — APPROVED** [review]

**Comment by rexim** [comment]
I'm gonna review that a bit later. Thanks!

**Comment by keddelzz** [comment]
Do we want to close #216 with this PR, too?

#216 describes two task:
(for conveinience I copy and pasted them here:)
- Pack std folder to the fatjar
- Develop a mechanism for discovering Morganey modules inside of zips?

But this issue already is sort of split:
1. This PR implements the first task
2. #222 deals with loading modules from the classpath

**Comment by rexim** [comment]
@keddelzz that's why I said that will review that later. Because I wanted to clean up this mess first. :)

**Comment by rexim** [comment]
@keddelzz I will try to find some time to do that today. Please bear with me.

**Comment by keddelzz** [comment]
> that's why I said that will review that later. Because I wanted to clean up this mess first. :)

Ah ok. I didn't know that!

> I will try to find some time to do that today. Please bear with me.

Please don't feel pushed! To push you was was not the intention of my question. :)

**Comment by rexim** [comment]
@keddelzz, it's ok you don't push me. I have to push myself all the time because I'm lazy as fuck. :D

Thanks for you comment. It actually helped me alot. You just showed me that #216 naturally becomes parent of #242 and #222. It's something I didn't see yesterday. Thank you very much!

**Comment by rexim** [comment]
It's actually my fault. To maintain issue tracker in a consistent state I have to clean it up periodically. Because issue tracker naturally becomes messy over time. I have a reminder to do that every Saturday, but I didn't do that (because as I already said I'm lazy as fuck), and here's the result. :)

I'll try to make sure it doesn't happen again.

**Review by rexim — APPROVED** [review]
LGTM :+1:

**Comment by rexim** [comment]
@keddelzz thanks for the changes!
@ForNeVeR @06needhamt  thanks for the review!

**Pull request merged**
