### PR TITLE
Classpath module discovery for MorganeyCompiler

### LINKED ISSUE #258: Use classpath modules in MorganeyCompiler
Split from https://github.com/morganey-lang/Morganey/issues/222#issuecomment-252682563

### PR DESCRIPTION
**Pull request by rexim**
### Description
- Rename MorganeyExecutor -> MorganeyCompiler
- Migrate MorganeyCompiler to the classpath module discovery mechanism 
### Checklist
- [X] Update docs
- [X] Add/Update Unit Tests

---

Close #258

### CODE REVIEW

**Review by keddelzz — APPROVED** [review]
LGTM 👍

**Comment by rexim** [comment]
It's pretty dangerous change. Assiging an extra pair of eyes on this one.

**Comment by ForNeVeR** [comment]
I'll take a look tonight.

**Review by ForNeVeR — APPROVED** [review]

**Comment by rexim** [comment]
@ForNeVeR @keddelzz thank you very much guys!

**Pull request merged**
