### PR TITLE
Windows funtests

### LINKED ISSUE #231: Funtests Windows support
Split from #55 

The problem is if you just uncomment [appveoyr.yml:10](https://github.com/morganey-lang/Morganey/blob/38defbbbb79aacb0f482967e3894acb2c46279f8/appveyor.yml#L10) the funtests hang on Appveyor

### PR DESCRIPTION
**Pull request by rexim**
Close #231

### CODE REVIEW

**Comment by rexim** [comment]
This PR has been aged perfectly!

@ForNeVeR @keddelzz please take a look at this one when you have a chance. :)

**Review by ForNeVeR — APPROVED** [review]
Purrfect.

**Review by keddelzz — APPROVED** [review]
:+1:

**Comment by rexim** [comment]
@ForNeVeR @keddelzz thank you guys for the review!

**Pull request merged**
