### PR TITLE
Add a couple of sample files

### PR DESCRIPTION
**Pull request by rexim**
Was just playing with Morganey and produced these two programs. To simply not lose them decided to put them in the repo.

They don't use std-lib because of some problems with dependent bindings #109. The problem should be resolved once #136 is implemented.

### CODE REVIEW

**Comment by rexim** [comment]
Maybe those samples will be used in functional testing in the future #55

**Comment by rexim** [comment]
Also this PR prepares the `docs` folder for #107 :)

**Comment by keddelzz** [comment]
Very nice! I love how readable the new notation is. 
LGTM :+1:

**Comment by ForNeVeR** [comment]
LGTM :+1:

**Comment by rexim** [comment]
@keddelzz @ForNeVeR thank you guys!

**Pull request merged**
