### PR TITLE
Enable Appveyor build system

### LINKED ISSUE #98: CI on Windows
Currently our build fails on Windows because of #93 and we cannot even see that. We need to perform CI on Windows as well. https://www.appveyor.com/ is probably fine.

### PR DESCRIPTION
**Pull request by ForNeVeR**
Closes #98.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Ah, wait, let me add a badge to the Readme file.

**Comment by ForNeVeR** [comment]
@rexim I don't think I have the way of adding the badges. Could you please add them yourself? They should be printed somewhere at https://ci.appveyor.com/project/rexim/morganey/settings/badges I think. Grab the "**master** branch status badge" from there.

**Comment by ForNeVeR** [comment]
And now you can merge :)

**Comment by rexim** [comment]
Travis didn't finishe yet!!

**Comment by rexim** [comment]
Remember how @Minoru broke the build by changing the README? We have to check everything!

**Comment by rexim** [comment]
Alright, LGTM! Thank you very much Mr @ForNeVeR!

**Comment by Minoru** [comment]
> Remember how @Minoru broke the build by changing the README?

BTW, I [recently did it again](http://0xd34df00d.me/logs/chat/codingteam@conference.jabber.ru/2016/07/18.html#02:54:56), this time by updating the CHANGELOG. (Turned out [Homebrew got refactored](https://github.com/akrennmair/newsbeuter/commit/b7cb95ea8285e5e0a73fb2d670f7a86778d2b5d6) a short while back.)

**Pull request merged**
