### PR TITLE
Tests for macros in meta subproject

### LINKED ISSUE #63: Testing macros in meta subproject on CI
Derived from discussion: https://github.com/rexim/Morganey/pull/61#discussion_r69382326

### PR DESCRIPTION
**Pull request by keddelzz**
Close #63

### CODE REVIEW

**Comment by rexim** [comment]
LGTM. Thanks!

**Comment by keddelzz** [comment]
I did some research why 

``` scala
m"\"Hello\""
```

is not working, I found out, that I treated escape sequences incorrectly.
(This problem did arise on your Sunday-stream.)

So I fixed this in the scope of this PR (59d3f0e). I'm sorry to say that the example shown above still doesn't work, because of a bug in scala ([SI-6476](https://issues.scala-lang.org/browse/SI-6476)). But \n, \t, \' etc are working correct now.

**Comment by rexim** [comment]
@keddelzz thank you for putting so much time and effort into that! It's totally fine if such functionality doesn't work right now because of a bug in the compiler. It's not critical. I'd suggest to create an issue for that. Something like "Escaped double quotes don't work in quasiquotation" and refer to SI-6476. Once the compiler's bug is fixed we gonna resolve our issue too.

The presence of such issue will show that we are aware of this bug, will serve as a reminder for ourselves and also as a place where people can complain if they encounter this problem during using Morganey. :)

**Comment by keddelzz** [comment]
Morganey is such a fun project, I'm totally hyped and very much interested in it. So of course I'll invest time in something I'm interested in. :)

**Pull request merged**
