### PR TITLE
Extend parser: add syntax sugar for pairs

### LINKED ISSUE #145: Syntax sugar for pairs
Derived from https://github.com/rexim/Morganey/pull/144#r76408716
### Scope
- [x] #224 Syntax support for pairs
- [x] #225 Pair smart detection

### PR DESCRIPTION
**Pull request by keddelzz**
splits #145

### CODE REVIEW

**Comment by rexim** [comment]
Thanks! I'll take a look tomorrow!

**Review by ForNeVeR — APPROVED** [review]

**Comment by rexim** [comment]
I believe the scope of #145 also included smart detection of pairs. https://github.com/morganey-lang/Morganey/pull/144#issuecomment-242774707

Sorry, it was my fault. I should've explicitly write that in the description of the issue. Let me fix that.

I suggest to Split #145  instead of closing it.

**Comment by rexim** [comment]
I'm gonna split #145 myself

**Review by rexim — APPROVED** [review]
LGTM :+1:

**Comment by rexim** [comment]
@ForNeVeR thanks for the review!
@keddelzz thanks for the changes!

**Pull request merged**
