### PR TITLE
Bump da version

### PR DESCRIPTION
**Pull request by rexim**
This PR just updates the version. The corresponding issue will be closed only after the artifacts are actually published to JCenter.

Related to #325

### CODE REVIEW

**Review by ForNeVeR — APPROVED** [review]

**Comment by ForNeVeR** [comment]
Something's wrong with our CI servers again :(

**Comment by rexim** [comment]
\*sigh\*

I'll take a look a bit later.

@ForNeVeR thanks for the review, though. :)

**Comment by rexim** [comment]
Yeah, I "fixed" it

**Comment by rexim** [comment]
Probably somehow related to #299. But now it also happens on Travis.

**Comment by rexim** [comment]
Alright, since it's a pretty trivial change, I think one reviewer is enough. I'm merging this and trying to publish `0.1.0`.

@keddelzz feel free to leave any remarks after the merge.

**Pull request merged**
