### PR TITLE
Make stdlib subproject build morganey module index

### LINKED ISSUE #304: Make stdlib subproject build morganey module index
Split from #257

### PR DESCRIPTION
**Pull request by keddelzz**
Generate the module-index of Morganey during the sbt-task 'build'.

closes #304

### CODE REVIEW

**Review by ForNeVeR — DISMISSED** [review]

**Comment by keddelzz** [comment]
It seems like the build timed out. I'm not sure why this happens, though.

**Comment by rexim** [comment]
@keddelzz yeah I restarted it. Will see if it passes this time. :)

**Comment by keddelzz** [comment]
@rexim, Thank's a lot!

**Review by rexim — APPROVED** [review]
LGTM, but will merge it a bit later, when we understand what's wrong with the CI.

**Comment by rexim** [comment]
@ForNeVeR thanks for the review!
@keddelzz thanks for the changes!

**Comment by ForNeVeR** [comment]
The tests are timed out on both of the CI servers. That's no coincidence; something really bad's happening. These're [Times of Ending](http://wh40k.lexicanum.com/wiki/Time_of_Ending) everyone is talking about...

**Comment by rexim** [comment]
I'm gonna check if the CI feels better tomorrow.

**Comment by rexim** [comment]
@keddelzz careful, I'm pushing to your branch.

**Comment by rexim** [comment]
@keddelzz do I understand correcly that the `build` command simply copies all of the jars to a single place for the sake of convenience and doesn't affect the compilation and testing processes anyhow?

**Comment by keddelzz** [comment]
> @keddelzz do I understand correcly that the build command simply copies all of the jars to a single place for the sake of convenience and doesn't affect the compilation and testing processes?

@rexim Exactly!

**Comment by rexim** [comment]
@keddelzz great! Thank you very much! Please review my additional changes when you get a chance.

**Comment by rexim** [comment]
@keddelzz ah, since you're the PR author you probably cannot use the GitHub's review mechanism. But please feel free to leave any comments if you feel something's off. :)

**Comment by keddelzz** [comment]
@rexim I approve your changes. Thank you very much for looking into the failed CI process!

**Review by ForNeVeR — APPROVED** [review]

**Comment by rexim** [comment]
@keddelzz @ForNeVeR thanks guys for the review!

**Pull request merged**
