### PR TITLE
Fix pretty-printer not handling precedence correctly

### LINKED ISSUE #188: The pretty-printer doesn't handle precedence correctly
### Steps to reproduce

```
λ> :raw [0]
λz.z λf.x.x λf.x.x
λ> λz.z λf.x.x λf.x.x
```
### Observed

```
term: λz.z (λf.x.x λf.x.x)
```
### Expected

```
numbers: [0]
```

### PR DESCRIPTION
**Pull request by keddelzz**
closes #188

### CODE REVIEW

**Comment by keddelzz** [comment]
For some reason travis can't find "org.scala-lang#scala-library;2.10.6" and all other dependencies for 2.10.6. I'm not sure why that's the case.

**Comment by rexim** [comment]
Something really strange is happening on Travis CI. I rebuilt some of the already succeeded builds and they failed. Investigating the problem...

**Comment by rexim** [comment]
Looks like everything got fixed by itself without #194 -_-

God dang it Travis! You're drunk!

**Comment by rexim** [comment]
@keddelzz, so, it's kind of a compromise between the shortest correct answer and the complexity of the implementation, right? :)

**Comment by rexim** [comment]
LGTM anyway :+1:

**Comment by ForNeVeR** [comment]
The resulting code is a very nice: we've excluded a special case and fixed the bug. LGTM 👍

**Comment by rexim** [comment]
@keddelzz thank you the fix!
@ForNeVeR thanks for the review!

**Pull request merged**
