### PR TITLE
Implement functions to construct ranges

### PR DESCRIPTION
**Pull request by keddelzz**
The parser still has to be extended to support creation of non-literal range literals. This falls in the scope of the issue #201.
## 

splits #120

### CODE REVIEW

**Comment by rexim** [comment]
Thanks! Looks really awesome! I'm gonna review that tomorrow.

It'd be great to have some funtests on that #55 But the funtests infrastructure is not merged to the master yet. :) So it can be done later separately.

**Review by ForNeVeR — APPROVED** [review]
Awesome 👍

**Comment by keddelzz** [comment]
> It'd be great to have some funtests on that #55 But the funtests infrastructure is not merged to the master yet. :) So it can be done later separately.

I created an issue for that. #204

**Comment by rexim** [comment]
It feels like the implementation of the range could be much faster

```
$ time cat test1.mgn | java -jar morganey.jar 
λ> load prelude
λ> 
λ> range 1 20
numbers: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
λ> 
real    0m16.993s
user    0m18.168s
sys 0m0.229s

------------------------------

$ time cat test2.mgn | java -jar morganey.jar 
λ> load prelude
λ> 
λ> range2 := Y (\rec.start.end. (le start end) (cons start (rec (succ start) end)) nil)
λ> range2 1 20
numbers: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
λ> 
real    0m0.855s
user    0m1.821s
sys 0m0.079s
```

I understand that the performance is not our primary concern, but c'mon. :) 10 times.

**Comment by rexim** [comment]
@keddelzz thanks for the improvement! I'm gonna take a look after the stream.

**Review by rexim — APPROVED** [review]
LGTM :+1: Thanks! It's nice to see how our std-lib grows. :)

**Pull request merged**
